### ISSUE TITLE
App won't work after updating from 0.11.2 to 0.12.3

### ISSUE THREAD

**Issue by nielscil** [anonaddy/docker#156]
#### Steps to reproduce this issue

1. Start instance of 0.12.3
2. Try connect app to instance using a token

#### Expected behaviour

> App should login and show aliasses etc.

#### Actual behaviour

> Showing error messages, Something went wrong.

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.16, build aa7e414
* Docker compose version if applicable (type `docker-compose --version`) :  docker-compose version 1.29.2, build unknown
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 18.04
* System info (type `uname -a`) : Linux <hostname> 5.4.0-1071-oracle # 77~18.04.1-Ubuntu SMP Mon Apr 25 13:42:26 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
 Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)

Server:
 Containers: 32
  Running: 32
  Paused: 0
  Stopped: 0
 Images: 763
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1071-oracle
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 23.44GiB
 Name: ***
 ID: ***
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

### Logs (docker)

```
anonaddy     | 172.28.205.128 - - [30/Jul/2022:08:45:39 +0000] "GET /api/v1/app-version HTTP/1.1" 500 44 "-" "Dalvik/2.1.0 (Linux; U; Android 11; HD1913 Build/RKQ1.201022.002)"
```

### Logs (laravel)

```
[2022-07-30 08:45:39] production.ERROR: Undefined array key 1 {"userId":"***","exception":"[object] (ErrorException(code: 0): Undefined array key 1 at /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1683)
[stacktrace]
#0 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(257): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(1683): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/anonaddy/app/Http/Controllers/Api/AppVersionController.php(17): Illuminate\\Support\\Collection->offsetGet()
#3 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\AppVersionController->index()
#4 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#5 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php(268): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#6 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php(211): Illuminate\\Routing\\Route->runController()
#7 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#8 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#9 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\EnsureEmailIsVerified->handle()
#11 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#13 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#15 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#16 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#17 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#19 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#21 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#22 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#23 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#24 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#25 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#26 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#28 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#29 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#31 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#32 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#34 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#36 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#38 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#40 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#42 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#43 /var/www/anonaddy/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#44 {main}
"}

```

### Extra
I think it's because from version 0.12.0 AnonAddy is checking it's version using git, but this doesn't work on the docker image. Therefore the version is empty (in WebGUI it's also empty) and the api-controller doesn't like it when trying to get values from the array in the [AppVersionController](https://github.com/anonaddy/anonaddy/blob/d7b40a9259155c8449db3b0a47485aa09b8dd7af/app/Http/Controllers/Api/AppVersionController.php#L17). Perhaps git should be installed in de docker image and the .git file of the reprository not removed or let AnonAddy check `ANONADDY_VERSION` environment variable?

**Comment by willbrowningme** [comment]
I've just pushed a new release [v0.13.2](https://github.com/anonaddy/anonaddy/releases/tag/v0.13.2) that I think will fix this. I agree though I need to add a way for the version to be retrieved from the Docker image too.

**Comment by crazy-max** [comment]
> I've just pushed a new release [v0.13.2](https://github.com/anonaddy/anonaddy/releases/tag/v0.13.2) that I think will fix this. I agree though I need to add a way for the version to be retrieved from the Docker image too.

@willbrowningme We have [`ANONADDY_VERSION` arg](https://github.com/anonaddy/docker/blob/3ed70537b25cd3bb68a10e17ad0e5a664f367733/Dockerfile#L1) that we could propagate as env var in the image if that SGTY?

**Comment by crazy-max** [comment]
Should be fixed with latest release: https://github.com/anonaddy/docker/releases/tag/0.13.3-r0

**Comment by nielscil** [comment]
> @nielscil Are you able to confirm this is fixed in the latest version?


The version controller doesn't give a HTTP 500 error anymore so the app works again. However the app gives a warning that the version of anonaddy is too low. I've checked the API with postman and it still doesn't return a version: 
`{
    "version": "",
    "major": 0,
    "minor": 0,
    "patch": 0
}`

Inside the docker-container is the env var available `ANONADDY_VERSION=0.13.3`. So there is still a bug somewhere.

**Comment by yurividal** [comment]
I can confirm 

> Inside the docker-container is the env var available `ANONADDY_VERSION=0.13.3`. So there is still a bug somewhere.

I can confirm that this is still present on 0.13.3

<img width="217" alt="image" src="https://user-images.githubusercontent.com/8555749/182153763-8d58b530-f660-4322-980a-7686dbffa8dd.png">

Blank version string on the web ui:
<img width="173" alt="image" src="https://user-images.githubusercontent.com/8555749/182153877-823d8c79-0aa6-411b-913d-a9aa4aeba31f.png">

My android APP also complains that the current version of anonaddy is too old.

**Comment by willbrowningme** [comment]
Hmm, so it seems that `getenv('ANONADDY_VERSION', true)` from the PHP code does not seem to work. I can try adding it to `app/config/anonaddy.php`, it could be due to the fact the running `php artisan config:cache` caches all env vars.

**Comment by willbrowningme** [comment]
The default domains considered stateful by Laravel Sanctum are:

```php
[
  "localhost",
  "localhost:3000",
  "127.0.0.1",
  "127.0.0.1:8000",
  "::1",
  "example.com"
]
```

As can be seen [here](https://github.com/anonaddy/anonaddy/blob/master/config/sanctum.php#L18), where example.com is the current app URL with port.

**Comment by crazy-max** [comment]
> `php artisan config:cache` caches all env vars.

Hum good point yes

**Comment by willbrowningme** [comment]
Hopefully this will be sorted in the latest release [https://github.com/anonaddy/anonaddy/releases/tag/v0.13.4](https://github.com/anonaddy/anonaddy/releases/tag/v0.13.4).

**Comment by nielscil** [comment]
@willbrowningme Yes, I can confirm it works with v0.13.4
